kind: pipeline
type: docker
name: default

clone:
  disable: true

steps:
- name: trigger-remote-command
  image: docker
  volumes:
  - name: ssh
    path: /drone/.ssh
  commands: 
    - ssh -p 22220 -i /drone/.ssh/id_rsa -F /drone/.ssh/ssh_config opt@172.105.217.99 '/home/opt/download.sh;/home/opt/voting/build.sh;/home/opt/voting/start.sh;exit;'
  when: 
    branch: 
    - main

volumes:
- name: ssh
  host:
    path: /volume1/docker/voting/ssh