kind: pipeline
type: docker
name: default

steps:
- name: npm-build
  privileged: true
  image: node:18-alpine
  volumes:
  - name: voting
    path: /drone/src/node_modules
  commands: 
    - npm install
    - npm run build
  when: 
    branch: 
    - main
- name: upload-to-masa
  image: docker
  commands: 
    - ssh --help

volumes:
- name: voting
  host:
    path: /volume1/docker/voting/node_modules