kind: pipeline
type: docker
name: default

steps:
- name: npm-build
  privileged: true
  image: node:18-alpine
  volumes:
  - name: voting
    path: /drone/src/node_modules
  commands: 
    - npm install
    - npm run build
  when: 
    branch: 
    - main
- name: upload-to-masa
  image: docker
  volumes:
  - name: ssh
    path: /drone/.ssh
  commands: 
    - cd /drone/.ssh  
    # - ssh-keygen -f /drone/.ssh/id_rsa -t rsa -C "bbgbbg0123@gmail.com"
    # - cat /drone/.ssh/id_rsa.pub
    - chmod 600 /drone/.ssh/id_rsa
    - ssh -p 22220 -i /drone/.ssh/id_rsa -F /drone/.ssh/ssh_config opt@172.105.217.99 'rm -rf /home/opt/voting; mkdir /home/opt/voting;'
    - scp -P 22220 -i /drone/.ssh/id_rsa -F /drone/.ssh/ssh_config -r /drone/src/* /drone/src/.next opt@172.105.217.99:/home/opt/voting 

volumes:
- name: voting
  host:
    path: /volume1/docker/voting/node_modules
- name: ssh
  host:
    path: /volume1/docker/voting/ssh